### PR TITLE
More responsive weather update

### PR DESCRIPTION
**Pull request by BakinDP**
**What was done:**
1. Swapped weird _WorldTickCallback_ with modern, identically weird _ServerTickEvents_
2. "Fixed" _ServerTickEvents_ behavior by tick division (every 2nd and 3rd ticks appear as impossible mix of different weather states, race may take place or idunno)
3. Implemented weather states and corresponding weather update function

**To do:**
1. Fix behavior of _ServerTickEvents_ or find better solution
2. Improve weather state tracking

### CODE REVIEW

**Comment by wVibzz** [comment]
yo thanks for this! 
I'm not going to add it just yet because I am currently updating to 0.5, if you want I am looking for some help if you want to add me on discord: vibzz

**Comment by BakinDP** [comment]
Sorry, I am not a Java developer and currently my help will be of not so much of use. I've studied things just to code this and still very strugling with understanding events and listeners (it's not a thing in C, lol). Once I overcome my difficulties, will join you right away!

**Comment by wVibzz** [comment]
no worries! ill try these out after i update and i might include it to 0.5, ill give credit aswell

**Review by wVibzz — APPROVED** [review]
credit to BakinDP

**Pull request merged**
